import dotenv from "dotenv";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getPool } from "../src/lib/db.ts";

const raizServer = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
dotenv.config({ path: path.join(raizServer, ".env") });

interface BarrioSeed {
  id: string;
  nombre: string;
  municipio: string;
  comuna: string | null;
  lat: number;
  lng: number;
  personas_est: number;
  es_albergue: boolean;
  via_abierta: boolean;
  alias: string[];
}

interface ReporteSeed {
  barrio_id: string;
  canal: "web";
  texto_crudo: string;
  dias_sin_agua: number | null;
  personas: number | null;
  sintomas: string[];
  casos: number;
  confianza: number;
  necesita_revision: boolean;
  sesion_id: string;
  dias_atras: number;
}

const barrios: BarrioSeed[] = [
  {
    id: "bue-lleras",
    nombre: "Lleras",
    municipio: "Buenaventura",
    comuna: "12",
    lat: 3.8892,
    lng: -77.0194,
    personas_est: 3200,
    es_albergue: false,
    via_abierta: true,
    alias: ["lleras", "el lleras", "yeras", "barrio yeras"],
  },
  {
    id: "bue-san-francisco",
    nombre: "San Francisco",
    municipio: "Buenaventura",
    comuna: "5",
    lat: 3.8861,
    lng: -77.0312,
    personas_est: 4100,
    es_albergue: false,
    via_abierta: true,
    alias: ["san francisco", "sanpetro", "san petro"],
  },
  {
    id: "bue-progreso",
    nombre: "El Progreso",
    municipio: "Buenaventura",
    comuna: "8",
    lat: 3.8754,
    lng: -77.0258,
    personas_est: 2800,
    es_albergue: false,
    via_abierta: true,
    alias: ["progreso", "el progreso"],
  },
  {
    id: "bue-independencia",
    nombre: "La Independencia",
    municipio: "Buenaventura",
    comuna: "7",
    lat: 3.882,
    lng: -77.0384,
    personas_est: 3600,
    es_albergue: false,
    via_abierta: false,
    alias: ["independencia", "la independencia"],
  },
  {
    id: "bue-pueblo-nuevo",
    nombre: "Pueblo Nuevo",
    municipio: "Buenaventura",
    comuna: "4",
    lat: 3.8702,
    lng: -77.0151,
    personas_est: 2500,
    es_albergue: false,
    via_abierta: true,
    alias: ["pueblo nuevo", "pueblonuevo"],
  },
  {
    id: "bue-juan23",
    nombre: "Juan XXIII",
    municipio: "Buenaventura",
    comuna: "6",
    lat: 3.8915,
    lng: -77.0287,
    personas_est: 1900,
    es_albergue: true,
    via_abierta: true,
    alias: ["juan 23", "juan xxiii", "juan veintitres"],
  },
  {
    id: "bue-napoles",
    nombre: "Nápoles",
    municipio: "Buenaventura",
    comuna: "9",
    lat: 3.8684,
    lng: -77.0356,
    personas_est: 2200,
    es_albergue: false,
    via_abierta: true,
    alias: ["napoles", "nápoles"],
  },
  {
    id: "bue-cristal",
    nombre: "El Cristal",
    municipio: "Buenaventura",
    comuna: "10",
    lat: 3.8788,
    lng: -77.0421,
    personas_est: 1700,
    es_albergue: false,
    via_abierta: true,
    alias: ["cristal", "el cristal"],
  },
  {
    id: "bue-cascajal",
    nombre: "Cascajal",
    municipio: "Buenaventura",
    comuna: "3",
    lat: 3.8951,
    lng: -77.0103,
    personas_est: 5400,
    es_albergue: false,
    via_abierta: true,
    alias: ["cascajal", "isla cascajal"],
  },
  {
    id: "bue-pianguita",
    nombre: "Piangüita",
    municipio: "Buenaventura",
    comuna: null,
    lat: 3.8419,
    lng: -77.2214,
    personas_est: 900,
    es_albergue: false,
    via_abierta: false,
    alias: ["pianguita", "piangüita"],
  },
  {
    id: "bue-inmaculada",
    nombre: "La Inmaculada",
    municipio: "Buenaventura",
    comuna: "11",
    lat: 3.8843,
    lng: -77.0228,
    personas_est: 2100,
    es_albergue: false,
    via_abierta: true,
    alias: ["inmaculada", "la inmaculada"],
  },
  {
    id: "bue-viento-libre",
    nombre: "Viento Libre",
    municipio: "Buenaventura",
    comuna: "2",
    lat: 3.8726,
    lng: -77.0089,
    personas_est: 1500,
    es_albergue: false,
    via_abierta: true,
    alias: ["viento libre", "vientolibre"],
  },
  {
    id: "qui-kennedy",
    nombre: "Kennedy",
    municipio: "Quibdó",
    comuna: "1",
    lat: 5.6924,
    lng: -76.6581,
    personas_est: 3800,
    es_albergue: false,
    via_abierta: true,
    alias: ["kennedy", "barrio kennedy"],
  },
  {
    id: "qui-yesquita",
    nombre: "Yesquita",
    municipio: "Quibdó",
    comuna: "2",
    lat: 5.6852,
    lng: -76.6654,
    personas_est: 2700,
    es_albergue: false,
    via_abierta: true,
    alias: ["yesquita", "yesca", "la yesca"],
  },
  {
    id: "qui-reposo",
    nombre: "El Reposo",
    municipio: "Quibdó",
    comuna: "3",
    lat: 5.6981,
    lng: -76.6512,
    personas_est: 1600,
    es_albergue: false,
    via_abierta: true,
    alias: ["reposo", "el reposo"],
  },
  {
    id: "qui-medrano",
    nombre: "Medrano",
    municipio: "Quibdó",
    comuna: "4",
    lat: 5.6887,
    lng: -76.6708,
    personas_est: 2300,
    es_albergue: false,
    via_abierta: false,
    alias: ["medrano", "barrio medrano"],
  },
  {
    id: "qui-alameda",
    nombre: "Alameda",
    municipio: "Quibdó",
    comuna: "5",
    lat: 5.6948,
    lng: -76.6483,
    personas_est: 3100,
    es_albergue: false,
    via_abierta: true,
    alias: ["alameda", "la alameda"],
  },
  {
    id: "qui-santo-domingo",
    nombre: "Santo Domingo",
    municipio: "Quibdó",
    comuna: "6",
    lat: 5.6814,
    lng: -76.6559,
    personas_est: 1200,
    es_albergue: true,
    via_abierta: true,
    alias: ["santo domingo", "santodomingo"],
  },
  {
    id: "qui-jardin",
    nombre: "Jardín",
    municipio: "Quibdó",
    comuna: "7",
    lat: 5.6992,
    lng: -76.6627,
    personas_est: 1800,
    es_albergue: false,
    via_abierta: true,
    alias: ["jardin", "jardín", "el jardin"],
  },
  {
    id: "bue-playita",
    nombre: "La Playita",
    municipio: "Buenaventura",
    comuna: "1",
    lat: 3.8805,
    lng: -77.0552,
    personas_est: 1400,
    es_albergue: false,
    via_abierta: true,
    alias: ["playita", "la playita"],
  },
];

const reportes: ReporteSeed[] = [
  {
    barrio_id: "bue-lleras",
    canal: "web",
    texto_crudo:
      "vecinos en el lleras llevamos 6 días sin una gota, somos como 300 personas aquí en la cuadra",
    dias_sin_agua: 6,
    personas: 300,
    sintomas: [],
    casos: 0,
    confianza: 0.88,
    necesita_revision: false,
    sesion_id: "11111111-1111-4111-8111-111111111111",
    dias_atras: 8,
  },
  {
    barrio_id: "bue-lleras",
    canal: "web",
    texto_crudo: "en yeras hay criaturas con diarrea, ya van 4 casos desde ayer",
    dias_sin_agua: 6,
    personas: null,
    sintomas: ["diarrea"],
    casos: 4,
    confianza: 0.72,
    necesita_revision: false,
    sesion_id: "11111111-1111-4111-8111-111111111112",
    dias_atras: 5,
  },
  {
    barrio_id: "bue-san-francisco",
    canal: "web",
    texto_crudo:
      "san francisco 4 dias sin acueducto, unas 50 familias pidiendo carrotanque",
    dias_sin_agua: 4,
    personas: 200,
    sintomas: [],
    casos: 0,
    confianza: 0.91,
    necesita_revision: false,
    sesion_id: "22222222-2222-4222-8222-222222222221",
    dias_atras: 20,
  },
  {
    barrio_id: "bue-progreso",
    canal: "web",
    texto_crudo: "el progreso lleva rato sin agua, el tanque está seco",
    dias_sin_agua: null,
    personas: null,
    sintomas: [],
    casos: 0,
    confianza: 0.41,
    necesita_revision: true,
    sesion_id: "33333333-3333-4333-8333-333333333331",
    dias_atras: 12,
  },
  {
    barrio_id: "bue-independencia",
    canal: "web",
    texto_crudo:
      "la independencia 7 días sin agua y la vía pa entrar está cerrada por el derrumbe",
    dias_sin_agua: 7,
    personas: null,
    sintomas: [],
    casos: 0,
    confianza: 0.84,
    necesita_revision: false,
    sesion_id: "44444444-4444-4444-8444-444444444441",
    dias_atras: 30,
  },
  {
    barrio_id: "bue-pueblo-nuevo",
    canal: "web",
    texto_crudo: "pueblo nuevo 2 días sin servicio, estamos al día casi",
    dias_sin_agua: 2,
    personas: 80,
    sintomas: [],
    casos: 0,
    confianza: 0.86,
    necesita_revision: false,
    sesion_id: "55555555-5555-4555-8555-555555555551",
    dias_atras: 6,
  },
  {
    barrio_id: "bue-juan23",
    canal: "web",
    texto_crudo:
      "en el albergue de juan 23 hay 120 personas y llevamos 5 días sin agua potable",
    dias_sin_agua: 5,
    personas: 120,
    sintomas: [],
    casos: 0,
    confianza: 0.9,
    necesita_revision: false,
    sesion_id: "66666666-6666-4666-8666-666666666661",
    dias_atras: 18,
  },
  {
    barrio_id: "bue-napoles",
    canal: "web",
    texto_crudo: "nápoles 3 días, la gente está cogiendo del estero y eso no es bueno",
    dias_sin_agua: 3,
    personas: null,
    sintomas: [],
    casos: 0,
    confianza: 0.77,
    necesita_revision: false,
    sesion_id: "77777777-7777-4777-8777-777777777771",
    dias_atras: 10,
  },
  {
    barrio_id: "bue-cristal",
    canal: "web",
    texto_crudo: "el cristal 8 días sin una gota, hay vómito y fiebre en 3 casas",
    dias_sin_agua: 8,
    personas: null,
    sintomas: ["vomito", "fiebre"],
    casos: 3,
    confianza: 0.81,
    necesita_revision: false,
    sesion_id: "88888888-8888-4888-8888-888888888881",
    dias_atras: 22,
  },
  {
    barrio_id: "bue-cascajal",
    canal: "web",
    texto_crudo: "cascajal 1 día sin agua no más, llegó un carrotanque ayer poquito",
    dias_sin_agua: 1,
    personas: 400,
    sintomas: [],
    casos: 0,
    confianza: 0.85,
    necesita_revision: false,
    sesion_id: "99999999-9999-4999-8999-999999999991",
    dias_atras: 4,
  },
  {
    barrio_id: "bue-pianguita",
    canal: "web",
    texto_crudo:
      "piangüita 9 días, la lancha no pasa y no hay cómo meter el carrotanque",
    dias_sin_agua: 9,
    personas: 90,
    sintomas: [],
    casos: 0,
    confianza: 0.83,
    necesita_revision: false,
    sesion_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
    dias_atras: 40,
  },
  {
    barrio_id: "bue-inmaculada",
    canal: "web",
    texto_crudo: "la inmaculada varios días ya, no sé cuántos, pero huele feo el pozo",
    dias_sin_agua: null,
    personas: null,
    sintomas: [],
    casos: 0,
    confianza: 0.35,
    necesita_revision: true,
    sesion_id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1",
    dias_atras: 9,
  },
  {
    barrio_id: "bue-viento-libre",
    canal: "web",
    texto_crudo: "viento libre 4 días sin agua, como 200 personas en el sector",
    dias_sin_agua: 4,
    personas: 200,
    sintomas: [],
    casos: 0,
    confianza: 0.87,
    necesita_revision: false,
    sesion_id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc1",
    dias_atras: 15,
  },
  {
    barrio_id: "qui-kennedy",
    canal: "web",
    texto_crudo: "kennedy en quibdó 5 días sin acueducto, mande el carro cisterna porfa",
    dias_sin_agua: 5,
    personas: null,
    sintomas: [],
    casos: 0,
    confianza: 0.89,
    necesita_revision: false,
    sesion_id: "dddddddd-dddd-4ddd-8ddd-ddddddddddd1",
    dias_atras: 11,
  },
  {
    barrio_id: "qui-yesquita",
    canal: "web",
    texto_crudo: "en la yesca hay 6 niños con diarrea, llevamos 6 días sin agua",
    dias_sin_agua: 6,
    personas: null,
    sintomas: ["diarrea"],
    casos: 6,
    confianza: 0.8,
    necesita_revision: false,
    sesion_id: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee1",
    dias_atras: 7,
  },
  {
    barrio_id: "qui-reposo",
    canal: "web",
    texto_crudo: "el reposo 2 días, todavía hay un tanque comunitario a medias",
    dias_sin_agua: 2,
    personas: 60,
    sintomas: [],
    casos: 0,
    confianza: 0.82,
    necesita_revision: false,
    sesion_id: "ffffffff-ffff-4fff-8fff-fffffffffff1",
    dias_atras: 3,
  },
  {
    barrio_id: "qui-medrano",
    canal: "web",
    texto_crudo: "medrano 8 días y el puente está caído, no entra nadie",
    dias_sin_agua: 8,
    personas: 150,
    sintomas: [],
    casos: 0,
    confianza: 0.86,
    necesita_revision: false,
    sesion_id: "10101010-1010-4101-8101-101010101011",
    dias_atras: 28,
  },
  {
    barrio_id: "qui-alameda",
    canal: "web",
    texto_crudo: "alameda 3 días sin agua, unas 40 familias",
    dias_sin_agua: 3,
    personas: 160,
    sintomas: [],
    casos: 0,
    confianza: 0.9,
    necesita_revision: false,
    sesion_id: "12121212-1212-4121-8121-121212121211",
    dias_atras: 14,
  },
  {
    barrio_id: "qui-santo-domingo",
    canal: "web",
    texto_crudo:
      "albergue santo domingo 7 días, hay adultos mayores y 80 personas refugiadas",
    dias_sin_agua: 7,
    personas: 80,
    sintomas: [],
    casos: 0,
    confianza: 0.88,
    necesita_revision: false,
    sesion_id: "13131313-1313-4131-8131-131313131311",
    dias_atras: 16,
  },
  {
    barrio_id: "qui-jardin",
    canal: "web",
    texto_crudo: "el jardín 1 día sin agua, casi normal",
    dias_sin_agua: 1,
    personas: 40,
    sintomas: [],
    casos: 0,
    confianza: 0.84,
    necesita_revision: false,
    sesion_id: "14141414-1414-4141-8141-141414141411",
    dias_atras: 2,
  },
  {
    barrio_id: "bue-playita",
    canal: "web",
    texto_crudo: "la playita 5 días, la gente está tomando del mar y eso no se puede",
    dias_sin_agua: 5,
    personas: 110,
    sintomas: [],
    casos: 0,
    confianza: 0.79,
    necesita_revision: false,
    sesion_id: "15151515-1515-4151-8151-151515151511",
    dias_atras: 19,
  },
  {
    barrio_id: "bue-lleras",
    canal: "web",
    texto_crudo: "otra vez el lleras, siguen sin agua, ya van 2 con vómito",
    dias_sin_agua: 6,
    personas: null,
    sintomas: ["vomito"],
    casos: 2,
    confianza: 0.74,
    necesita_revision: false,
    sesion_id: "16161616-1616-4161-8161-161616161611",
    dias_atras: 1,
  },
  {
    barrio_id: "bue-san-francisco",
    canal: "web",
    texto_crudo: "sanpetro o san francisco? 4 días igual, 500 personas más o menos",
    dias_sin_agua: 4,
    personas: 500,
    sintomas: [],
    casos: 0,
    confianza: 0.52,
    necesita_revision: true,
    sesion_id: "17171717-1717-4171-8171-171717171711",
    dias_atras: 25,
  },
  {
    barrio_id: "bue-progreso",
    canal: "web",
    texto_crudo: "progreso 3 días ya, confirmo, ayer no llegó nadie",
    dias_sin_agua: 3,
    personas: 90,
    sintomas: [],
    casos: 0,
    confianza: 0.8,
    necesita_revision: false,
    sesion_id: "18181818-1818-4181-8181-181818181811",
    dias_atras: 8,
  },
  {
    barrio_id: "qui-kennedy",
    canal: "web",
    texto_crudo: "kennedy hay fiebre en 5 casas, 5 días sin agua todavía",
    dias_sin_agua: 5,
    personas: null,
    sintomas: ["fiebre"],
    casos: 5,
    confianza: 0.78,
    necesita_revision: false,
    sesion_id: "19191919-1919-4191-8191-191919191911",
    dias_atras: 6,
  },
  {
    barrio_id: "qui-yesquita",
    canal: "web",
    texto_crudo: "yesquita el carrotanque no ha venido, 6 días y diarrea sigue",
    dias_sin_agua: 6,
    personas: 220,
    sintomas: ["diarrea"],
    casos: 3,
    confianza: 0.83,
    necesita_revision: false,
    sesion_id: "20202020-2020-4202-8202-202020202021",
    dias_atras: 2,
  },
  {
    barrio_id: "bue-cascajal",
    canal: "web",
    texto_crudo: "en cascajal hay agua otra vez, llegó anoche el de la alcaldía",
    dias_sin_agua: 0,
    personas: 5400,
    sintomas: [],
    casos: 0,
    confianza: 0.7,
    necesita_revision: false,
    sesion_id: "21212121-2121-4212-8212-212121212121",
    dias_atras: 1,
  },
  {
    barrio_id: "bue-napoles",
    canal: "web",
    texto_crudo: "nápoles reportando diarrea, 2 casos, 3 días sin tubería",
    dias_sin_agua: 3,
    personas: null,
    sintomas: ["diarrea"],
    casos: 2,
    confianza: 0.76,
    necesita_revision: false,
    sesion_id: "23232323-2323-4232-8232-232323232321",
    dias_atras: 4,
  },
  {
    barrio_id: "qui-alameda",
    canal: "web",
    texto_crudo: "alameda hace rato sin agua, un resto ya",
    dias_sin_agua: null,
    personas: null,
    sintomas: [],
    casos: 0,
    confianza: 0.28,
    necesita_revision: true,
    sesion_id: "24242424-2424-4242-8242-242424242421",
    dias_atras: 13,
  },
  {
    barrio_id: "qui-medrano",
    canal: "web",
    texto_crudo: "medrano 8 días, 3 con diarrea y 1 con vómito",
    dias_sin_agua: 8,
    personas: null,
    sintomas: ["diarrea", "vomito"],
    casos: 4,
    confianza: 0.81,
    necesita_revision: false,
    sesion_id: "25252525-2525-4252-8252-252525252521",
    dias_atras: 9,
  },
  {
    barrio_id: "bue-juan23",
    canal: "web",
    texto_crudo: "juan xxiii el albergue pide 2000 litros, 5 días ya",
    dias_sin_agua: 5,
    personas: 120,
    sintomas: [],
    casos: 0,
    confianza: 0.87,
    necesita_revision: false,
    sesion_id: "26262626-2626-4262-8262-262626262621",
    dias_atras: 3,
  },
  {
    barrio_id: "bue-independencia",
    canal: "web",
    texto_crudo: "independencia sigue la vía cerrada, 7 días, no hay cómo pasar",
    dias_sin_agua: 7,
    personas: 250,
    sintomas: [],
    casos: 0,
    confianza: 0.85,
    necesita_revision: false,
    sesion_id: "27272727-2727-4272-8272-272727272721",
    dias_atras: 6,
  },
  {
    barrio_id: "qui-santo-domingo",
    canal: "web",
    texto_crudo: "santo domingo 2 casos de diarrea en el albergue, 7 días sin agua",
    dias_sin_agua: 7,
    personas: 80,
    sintomas: ["diarrea"],
    casos: 2,
    confianza: 0.82,
    necesita_revision: false,
    sesion_id: "28282828-2828-4282-8282-282828282821",
    dias_atras: 4,
  },
  {
    barrio_id: "bue-playita",
    canal: "web",
    texto_crudo: "playita 5 días, como 30 familias",
    dias_sin_agua: 5,
    personas: 120,
    sintomas: [],
    casos: 0,
    confianza: 0.88,
    necesita_revision: false,
    sesion_id: "29292929-2929-4292-8292-292929292921",
    dias_atras: 10,
  },
  {
    barrio_id: "qui-jardin",
    canal: "web",
    texto_crudo: "jardín quibdó todo bien casi, 1 día nada más",
    dias_sin_agua: 1,
    personas: 40,
    sintomas: [],
    casos: 0,
    confianza: 0.8,
    necesita_revision: false,
    sesion_id: "30303030-3030-4303-8303-303030303031",
    dias_atras: 1,
  },
  {
    barrio_id: "bue-viento-libre",
    canal: "web",
    texto_crudo: "viento libre hay fiebre, 1 caso, 4 días sin agua",
    dias_sin_agua: 4,
    personas: null,
    sintomas: ["fiebre"],
    casos: 1,
    confianza: 0.73,
    necesita_revision: false,
    sesion_id: "31313131-3131-4313-8313-313131313131",
    dias_atras: 5,
  },
  {
    barrio_id: "bue-cristal",
    canal: "web",
    texto_crudo: "el cristal crítico, 8 días, 4 con diarrea ahora",
    dias_sin_agua: 8,
    personas: 70,
    sintomas: ["diarrea"],
    casos: 4,
    confianza: 0.86,
    necesita_revision: false,
    sesion_id: "32323232-3232-4323-8323-323232323231",
    dias_atras: 3,
  },
  {
    barrio_id: "qui-reposo",
    canal: "web",
    texto_crudo: "reposo 2 días, todo tranquilo todavía",
    dias_sin_agua: 2,
    personas: 60,
    sintomas: [],
    casos: 0,
    confianza: 0.84,
    necesita_revision: false,
    sesion_id: "33333333-3333-4333-8333-333333333332",
    dias_atras: 2,
  },
  {
    barrio_id: "bue-pueblo-nuevo",
    canal: "web",
    texto_crudo: "pueblo nuevo 2 días, 15 familias en la parte de abajo",
    dias_sin_agua: 2,
    personas: 60,
    sintomas: [],
    casos: 0,
    confianza: 0.85,
    necesita_revision: false,
    sesion_id: "34343434-3434-4343-8343-343434343431",
    dias_atras: 7,
  },
  {
    barrio_id: "bue-pianguita",
    canal: "web",
    texto_crudo: "pianguita 9 días, 2 con vómito, la vía por mar está brava",
    dias_sin_agua: 9,
    personas: 90,
    sintomas: ["vomito"],
    casos: 2,
    confianza: 0.8,
    necesita_revision: false,
    sesion_id: "35353535-3535-4353-8353-353535353531",
    dias_atras: 8,
  },
];

async function seed(): Promise<void> {
  const pool = getPool();
  const client = await pool.connect();
  try {
    await client.query("begin");
    await client.query(
      "truncate reportes, entregas, rutas, alertas_salud restart identity cascade",
    );

    for (const b of barrios) {
      await client.query(
        `insert into barrios (
           id, nombre, municipio, comuna, lat, lng, personas_est,
           es_albergue, via_abierta, alias
         ) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
         on conflict (id) do update set
           nombre = excluded.nombre,
           municipio = excluded.municipio,
           comuna = excluded.comuna,
           lat = excluded.lat,
           lng = excluded.lng,
           personas_est = excluded.personas_est,
           es_albergue = excluded.es_albergue,
           via_abierta = excluded.via_abierta,
           alias = excluded.alias`,
        [
          b.id,
          b.nombre,
          b.municipio,
          b.comuna,
          b.lat,
          b.lng,
          b.personas_est,
          b.es_albergue,
          b.via_abierta,
          b.alias,
        ],
      );
    }

    for (const r of reportes) {
      await client.query(
        `insert into reportes (
           barrio_id, canal, texto_crudo, dias_sin_agua, personas,
           sintomas, casos, confianza, necesita_revision, sesion_id, created_at
         ) values (
           $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
           now() - ($11::text || ' days')::interval
         )`,
        [
          r.barrio_id,
          r.canal,
          r.texto_crudo,
          r.dias_sin_agua,
          r.personas,
          r.sintomas,
          r.casos,
          r.confianza,
          r.necesita_revision,
          r.sesion_id,
          String(r.dias_sin_agua ?? 3),
        ],
      );
    }

    await client.query(
      `insert into entregas (barrio_id, carrotanque, litros, confirmada_por, created_at)
       values
         ('bue-cascajal', 'CT-01', 8000, 'comunidad', now() - interval '6 hours'),
         ('qui-jardin', 'CT-02', 3000, 'conductor', now() - interval '4 hours')`,
    );

    await client.query("commit");
    const nBarrios = await client.query<{ count: string }>(
      "select count(*)::text as count from barrios",
    );
    const nReportes = await client.query<{ count: string }>(
      "select count(*)::text as count from reportes",
    );
    console.log(
      `Seed ok: ${nBarrios.rows[0].count} barrios, ${nReportes.rows[0].count} reportes`,
    );
  } catch (err: unknown) {
    await client.query("rollback");
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seed().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
